// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Action is the predicate function for action builders.
type Action func(*sql.Selector)

// Bot is the predicate function for bot builders.
type Bot func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
