// Code generated by entc, DO NOT EDIT.

package bot

const (
	// Label holds the string label denoting the bot type in the database.
	Label = "bot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldInterval holds the string denoting the interval field in the database.
	FieldInterval = "interval"
	// FieldDelta holds the string denoting the delta field in the database.
	FieldDelta = "delta"
	// FieldLastSeen holds the string denoting the lastseen field in the database.
	FieldLastSeen = "last_seen"

	// EdgeInfecting holds the string denoting the infecting edge name in mutations.
	EdgeInfecting = "infecting"

	// Table holds the table name of the bot in the database.
	Table = "bots"
	// InfectingTable is the table the holds the infecting relation/edge. The primary key declared below.
	InfectingTable = "host_bots"
	// InfectingInverseTable is the table name for the Host entity.
	// It exists in this package in order to avoid circular dependency with the "host" package.
	InfectingInverseTable = "hosts"
)

// Columns holds all SQL columns for bot fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldInterval,
	FieldDelta,
	FieldLastSeen,
}

var (
	// InfectingPrimaryKey and InfectingColumn2 are the table columns denoting the
	// primary key for the infecting relation (M2M).
	InfectingPrimaryKey = []string{"host_id", "bot_id"}
)

var (
	// IntervalValidator is a validator for the "interval" field. It is called by the builders before save.
	IntervalValidator func(int) error
	// DeltaValidator is a validator for the "delta" field. It is called by the builders before save.
	DeltaValidator func(int) error
	// LastSeenValidator is a validator for the "lastSeen" field. It is called by the builders before save.
	LastSeenValidator func(int) error
)
