// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/degenerat3/meteor/meteor/core/ent/bot"
	"github.com/degenerat3/meteor/meteor/core/ent/host"
	"github.com/degenerat3/meteor/meteor/core/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	botFields := schema.Bot{}.Fields()
	_ = botFields
	// botDescInterval is the schema descriptor for interval field.
	botDescInterval := botFields[1].Descriptor()
	// bot.IntervalValidator is a validator for the "interval" field. It is called by the builders before save.
	bot.IntervalValidator = botDescInterval.Validators[0].(func(int) error)
	// botDescDelta is the schema descriptor for delta field.
	botDescDelta := botFields[2].Descriptor()
	// bot.DeltaValidator is a validator for the "delta" field. It is called by the builders before save.
	bot.DeltaValidator = botDescDelta.Validators[0].(func(int) error)
	// botDescLastSeen is the schema descriptor for lastSeen field.
	botDescLastSeen := botFields[3].Descriptor()
	// bot.LastSeenValidator is a validator for the "lastSeen" field. It is called by the builders before save.
	bot.LastSeenValidator = botDescLastSeen.Validators[0].(func(int) error)
	hostFields := schema.Host{}.Fields()
	_ = hostFields
	// hostDescLastSeen is the schema descriptor for lastSeen field.
	hostDescLastSeen := hostFields[2].Descriptor()
	// host.LastSeenValidator is a validator for the "lastSeen" field. It is called by the builders before save.
	host.LastSeenValidator = hostDescLastSeen.Validators[0].(func(int) error)
}
