// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// ActionsColumns holds the columns for the "actions" table.
	ActionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString},
		{Name: "mode", Type: field.TypeString},
		{Name: "args", Type: field.TypeString},
		{Name: "queued", Type: field.TypeBool},
		{Name: "responded", Type: field.TypeBool},
		{Name: "result", Type: field.TypeString},
	}
	// ActionsTable holds the schema information for the "actions" table.
	ActionsTable = &schema.Table{
		Name:        "actions",
		Columns:     ActionsColumns,
		PrimaryKey:  []*schema.Column{ActionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// BotsColumns holds the columns for the "bots" table.
	BotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString},
		{Name: "interval", Type: field.TypeInt},
		{Name: "delta", Type: field.TypeInt},
		{Name: "last_seen", Type: field.TypeInt},
	}
	// BotsTable holds the schema information for the "bots" table.
	BotsTable = &schema.Table{
		Name:        "bots",
		Columns:     BotsColumns,
		PrimaryKey:  []*schema.Column{BotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:        "groups",
		Columns:     GroupsColumns,
		PrimaryKey:  []*schema.Column{GroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// HostsColumns holds the columns for the "hosts" table.
	HostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hostname", Type: field.TypeString},
		{Name: "interface", Type: field.TypeString},
		{Name: "last_seen", Type: field.TypeInt},
	}
	// HostsTable holds the schema information for the "hosts" table.
	HostsTable = &schema.Table{
		Name:        "hosts",
		Columns:     HostsColumns,
		PrimaryKey:  []*schema.Column{HostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// GroupMembersColumns holds the columns for the "group_members" table.
	GroupMembersColumns = []*schema.Column{
		{Name: "group_id", Type: field.TypeInt},
		{Name: "host_id", Type: field.TypeInt},
	}
	// GroupMembersTable holds the schema information for the "group_members" table.
	GroupMembersTable = &schema.Table{
		Name:       "group_members",
		Columns:    GroupMembersColumns,
		PrimaryKey: []*schema.Column{GroupMembersColumns[0], GroupMembersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "group_members_group_id",
				Columns: []*schema.Column{GroupMembersColumns[0]},

				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "group_members_host_id",
				Columns: []*schema.Column{GroupMembersColumns[1]},

				RefColumns: []*schema.Column{HostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// HostBotsColumns holds the columns for the "host_bots" table.
	HostBotsColumns = []*schema.Column{
		{Name: "host_id", Type: field.TypeInt},
		{Name: "bot_id", Type: field.TypeInt},
	}
	// HostBotsTable holds the schema information for the "host_bots" table.
	HostBotsTable = &schema.Table{
		Name:       "host_bots",
		Columns:    HostBotsColumns,
		PrimaryKey: []*schema.Column{HostBotsColumns[0], HostBotsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "host_bots_host_id",
				Columns: []*schema.Column{HostBotsColumns[0]},

				RefColumns: []*schema.Column{HostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "host_bots_bot_id",
				Columns: []*schema.Column{HostBotsColumns[1]},

				RefColumns: []*schema.Column{BotsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// HostActionsColumns holds the columns for the "host_actions" table.
	HostActionsColumns = []*schema.Column{
		{Name: "host_id", Type: field.TypeInt},
		{Name: "action_id", Type: field.TypeInt},
	}
	// HostActionsTable holds the schema information for the "host_actions" table.
	HostActionsTable = &schema.Table{
		Name:       "host_actions",
		Columns:    HostActionsColumns,
		PrimaryKey: []*schema.Column{HostActionsColumns[0], HostActionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "host_actions_host_id",
				Columns: []*schema.Column{HostActionsColumns[0]},

				RefColumns: []*schema.Column{HostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "host_actions_action_id",
				Columns: []*schema.Column{HostActionsColumns[1]},

				RefColumns: []*schema.Column{ActionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActionsTable,
		BotsTable,
		GroupsTable,
		HostsTable,
		GroupMembersTable,
		HostBotsTable,
		HostActionsTable,
	}
)

func init() {
	GroupMembersTable.ForeignKeys[0].RefTable = GroupsTable
	GroupMembersTable.ForeignKeys[1].RefTable = HostsTable
	HostBotsTable.ForeignKeys[0].RefTable = HostsTable
	HostBotsTable.ForeignKeys[1].RefTable = BotsTable
	HostActionsTable.ForeignKeys[0].RefTable = HostsTable
	HostActionsTable.ForeignKeys[1].RefTable = ActionsTable
}
