// This file holds the proto message formats for interacting with the core API endpoints

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: mcs.proto

package mcs

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Meteor Communication Standard
type MCS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int32     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`      // HTTP Status Code
	Uuid      string    `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`           // UUID for Bot or Action UUI
	Hostname  string    `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`   // hostname
	Groupname string    `protobuf:"bytes,4,opt,name=groupname,proto3" json:"groupname,omitempty"` // group name
	Mode      string    `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`           // the action mode (shell, scrshot, etc)
	Interface string    `protobuf:"bytes,6,opt,name=interface,proto3" json:"interface,omitempty"` // the network interface of the host
	Desc      string    `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`           // description for group or API response
	Args      string    `protobuf:"bytes,8,opt,name=args,proto3" json:"args,omitempty"`           // the data of the action (command line args, bot uuid, etc)
	Result    string    `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`       // the result of an action (usually command output)
	Interval  int32     `protobuf:"varint,10,opt,name=interval,proto3" json:"interval,omitempty"` // callback interval
	Delta     int32     `protobuf:"varint,11,opt,name=delta,proto3" json:"delta,omitempty"`       // jitter for interval
	Actions   []*Action `protobuf:"bytes,12,rep,name=actions,proto3" json:"actions,omitempty"`    // array of Actions
}

func (x *MCS) Reset() {
	*x = MCS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCS) ProtoMessage() {}

func (x *MCS) ProtoReflect() protoreflect.Message {
	mi := &file_mcs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCS.ProtoReflect.Descriptor instead.
func (*MCS) Descriptor() ([]byte, []int) {
	return file_mcs_proto_rawDescGZIP(), []int{0}
}

func (x *MCS) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MCS) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MCS) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MCS) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *MCS) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *MCS) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *MCS) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *MCS) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *MCS) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *MCS) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *MCS) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *MCS) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

// Actions to be run by the bot
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // the UUID of the action
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // type of data that will be in "args" or is being requested
	Args string `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"` // the data of the action (command line args, bot uuid, etc)
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_mcs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_mcs_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Action) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Action) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

var File_mcs_proto protoreflect.FileDescriptor

var file_mcs_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb2, 0x02, 0x0a, 0x03,
	0x4d, 0x43, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x21, 0x0a,
	0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x44, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mcs_proto_rawDescOnce sync.Once
	file_mcs_proto_rawDescData = file_mcs_proto_rawDesc
)

func file_mcs_proto_rawDescGZIP() []byte {
	file_mcs_proto_rawDescOnce.Do(func() {
		file_mcs_proto_rawDescData = protoimpl.X.CompressGZIP(file_mcs_proto_rawDescData)
	})
	return file_mcs_proto_rawDescData
}

var file_mcs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcs_proto_goTypes = []interface{}{
	(*MCS)(nil),    // 0: MCS
	(*Action)(nil), // 1: Action
}
var file_mcs_proto_depIdxs = []int32{
	1, // 0: MCS.actions:type_name -> Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcs_proto_init() }
func file_mcs_proto_init() {
	if File_mcs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mcs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mcs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mcs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcs_proto_goTypes,
		DependencyIndexes: file_mcs_proto_depIdxs,
		MessageInfos:      file_mcs_proto_msgTypes,
	}.Build()
	File_mcs_proto = out.File
	file_mcs_proto_rawDesc = nil
	file_mcs_proto_goTypes = nil
	file_mcs_proto_depIdxs = nil
}
