// Code generated by entc, DO NOT EDIT.

package host

const (
	// Label holds the string label denoting the host type in the database.
	Label = "host"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldInterface holds the string denoting the interface field in the database.
	FieldInterface = "interface"
	// FieldLastSeen holds the string denoting the lastseen field in the database.
	FieldLastSeen = "last_seen"

	// EdgeBots holds the string denoting the bots edge name in mutations.
	EdgeBots = "bots"
	// EdgeActions holds the string denoting the actions edge name in mutations.
	EdgeActions = "actions"
	// EdgeMember holds the string denoting the member edge name in mutations.
	EdgeMember = "member"

	// Table holds the table name of the host in the database.
	Table = "hosts"
	// BotsTable is the table the holds the bots relation/edge. The primary key declared below.
	BotsTable = "host_bots"
	// BotsInverseTable is the table name for the Bot entity.
	// It exists in this package in order to avoid circular dependency with the "bot" package.
	BotsInverseTable = "bots"
	// ActionsTable is the table the holds the actions relation/edge. The primary key declared below.
	ActionsTable = "host_actions"
	// ActionsInverseTable is the table name for the Action entity.
	// It exists in this package in order to avoid circular dependency with the "action" package.
	ActionsInverseTable = "actions"
	// MemberTable is the table the holds the member relation/edge. The primary key declared below.
	MemberTable = "group_members"
	// MemberInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	MemberInverseTable = "groups"
)

// Columns holds all SQL columns for host fields.
var Columns = []string{
	FieldID,
	FieldHostname,
	FieldInterface,
	FieldLastSeen,
}

var (
	// BotsPrimaryKey and BotsColumn2 are the table columns denoting the
	// primary key for the bots relation (M2M).
	BotsPrimaryKey = []string{"host_id", "bot_id"}
	// ActionsPrimaryKey and ActionsColumn2 are the table columns denoting the
	// primary key for the actions relation (M2M).
	ActionsPrimaryKey = []string{"host_id", "action_id"}
	// MemberPrimaryKey and MemberColumn2 are the table columns denoting the
	// primary key for the member relation (M2M).
	MemberPrimaryKey = []string{"group_id", "host_id"}
)

var (
	// LastSeenValidator is a validator for the "lastSeen" field. It is called by the builders before save.
	LastSeenValidator func(int) error
)
